const fs = require('fs').promises;
const path = require('path');

// Comprehensive fresh data scraped on 14 Nov 2025
const COMPREHENSIVE_DATA = {
  'hdfc-mid-cap-fund-direct-growth': {
    url: 'https://groww.in/mutual-funds/hdfc-mid-cap-fund-direct-growth',
    name: 'HDFC Mid Cap Fund Direct Growth',
    category: 'Equity Mid Cap',
    risk_level: 'Very High Risk',
    nav: '224.35',
    nav_date: '14 Nov 2025',
    rating: '5',
    expense_ratio: '0.71',
    exit_load: '1% if redeemed within 1 year from the date of allotment',
    min_sip: '100',
    min_investment: '100',
    fund_size: '89,383.23 Cr',
    lock_in: 'No lock-in',
    lock_in_years: 0,
    returns_1y: '12.5',
    returns_3y: '27.0',
    returns_5y: '29.2',
    returns_all: '21.2',
    fund_manager: 'Information not available in scheme factsheet',
    benchmark: 'Nifty Midcap 150 TRI',
    top_holdings: 'Max Financial Services Ltd. (4.46%), AU Small Finance Bank Ltd. (3.70%), Indian Bank (3.54%), The Federal Bank Ltd. (3.38%), Balkrishna Industries Ltd. (3.37%)',
    total_holdings: '75',
    portfolio_summary: 'Diversified across Financial (multiple banks), Automobile, Healthcare, Technology, Energy sectors',
    tax_ltcg: '12.5% on gains above ₹1.25 lakh/year for holdings > 12 months',
    tax_stcg: '20% on gains for holdings ≤ 12 months'
  },
  'hdfc-large-cap-fund-direct-growth': {
    url: 'https://groww.in/mutual-funds/hdfc-large-cap-fund-direct-growth',
    name: 'HDFC Large Cap Fund Direct Growth',
    category: 'Equity Large Cap',
    risk_level: 'Very High Risk',
    nav: '1,268.60',
    nav_date: '14 Nov 2025',
    rating: '5',
    expense_ratio: '0.97',
    exit_load: '1% if redeemed within 1 year from the date of allotment',
    min_sip: '100',
    min_investment: '100',
    fund_size: '39,779.26 Cr',
    lock_in: 'No lock-in',
    lock_in_years: 0,
    returns_1y: '8.2',
    returns_3y: '16.4',
    returns_5y: '20.2',
    returns_all: '14.2',
    fund_manager: 'Information not available in scheme factsheet',
    benchmark: 'Nifty 50 TRI',
    top_holdings: 'HDFC Bank Ltd. (9.49%), ICICI Bank Ltd. (8.80%), Bharti Airtel Ltd. (6.16%), Reliance Industries Ltd. (5.77%), Titan Company Ltd. (3.88%)',
    total_holdings: '49',
    portfolio_summary: 'Focus on large-cap blue chip companies across Financial, Technology, Telecom, Energy sectors',
    tax_ltcg: '12.5% on gains above ₹1.25 lakh/year for holdings > 12 months',
    tax_stcg: '20% on gains for holdings ≤ 12 months'
  },
  'hdfc-small-cap-fund-direct-growth': {
    url: 'https://groww.in/mutual-funds/hdfc-small-cap-fund-direct-growth',
    name: 'HDFC Small Cap Fund Direct Growth',
    category: 'Equity Small Cap',
    risk_level: 'Very High Risk',
    nav: '162.41',
    nav_date: '14 Nov 2025',
    rating: '4',
    expense_ratio: '0.82',
    exit_load: '1% if redeemed within 1 year from the date of allotment',
    min_sip: '100',
    min_investment: '100',
    fund_size: '38,412.10 Cr',
    lock_in: 'No lock-in',
    lock_in_years: 0,
    returns_1y: '7.1',
    returns_3y: '23.2',
    returns_5y: '30.0',
    returns_all: '19.8',
    fund_manager: 'Information not available in scheme factsheet',
    benchmark: 'Nifty Smallcap 250 TRI',
    top_holdings: 'Firstsource Solutions Ltd. (5.09%), eClerx Services Ltd. (4.46%), Aster DM Healthcare Ltd. (4.22%), Bank Of Baroda (3.39%), Gabriel India Ltd. (3.14%)',
    total_holdings: '82',
    portfolio_summary: 'Diversified small-cap portfolio across Services, Healthcare, Financial, Automobile, Technology sectors',
    tax_ltcg: '12.5% on gains above ₹1.25 lakh/year for holdings > 12 months',
    tax_stcg: '20% on gains for holdings ≤ 12 months'
  },
  'hdfc-equity-fund-direct-growth': {
    url: 'https://groww.in/mutual-funds/hdfc-equity-fund-direct-growth',
    name: 'HDFC Flexi Cap Direct Plan Growth',
    category: 'Equity Flexi Cap',
    risk_level: 'Very High Risk',
    nav: '2,263.97',
    nav_date: '14 Nov 2025',
    rating: '5',
    expense_ratio: '0.67',
    exit_load: '1% if redeemed within 1 year from the date of allotment',
    min_sip: '100',
    min_investment: '100',
    fund_size: '91,041.00 Cr',
    lock_in: 'No lock-in',
    lock_in_years: 0,
    returns_1y: '12.9',
    returns_3y: '22.4',
    returns_5y: '27.4',
    returns_all: '17.1',
    fund_manager: 'Information not available in scheme factsheet',
    benchmark: 'Nifty 500 Multicap 50:25:25 TRI',
    top_holdings: 'ICICI Bank Ltd. (9.01%), HDFC Bank Ltd. (8.57%), Axis Bank Ltd. (7.31%), State Bank of India (4.53%), SBI Life Insurance Company Ltd. (4.30%)',
    total_holdings: '55',
    portfolio_summary: 'Flexible allocation across large, mid, and small-cap stocks, focused on Financial, Auto, Healthcare sectors',
    tax_ltcg: '12.5% on gains above ₹1.25 lakh/year for holdings > 12 months',
    tax_stcg: '20% on gains for holdings ≤ 12 months'
  },
  'hdfc-elss-tax-saver-fund-direct-plan-growth': {
    url: 'https://groww.in/mutual-funds/hdfc-elss-tax-saver-fund-direct-plan-growth',
    name: 'HDFC ELSS Tax Saver Fund Direct Plan Growth',
    category: 'Equity ELSS',
    risk_level: 'Very High Risk',
    nav: '1,574.10',
    nav_date: '14 Nov 2025',
    rating: '5',
    expense_ratio: '1.08',
    exit_load: 'No exit load (3 year mandatory lock-in applies)',
    min_sip: '500',
    min_investment: '500',
    fund_size: '17,194.16 Cr',
    lock_in: '3 years (mandatory)',
    lock_in_years: 3,
    returns_1y: '11.6',
    returns_3y: '21.8',
    returns_5y: '24.8',
    returns_all: '15.5',
    fund_manager: 'Information not available in scheme factsheet',
    benchmark: 'Nifty 500 TRI',
    tax_benefit: 'Tax deduction under Section 80C up to ₹1.5 lakh per financial year',
    top_holdings: 'HDFC Bank Ltd. (9.53%), ICICI Bank Ltd. (8.61%), Axis Bank Ltd. (8.60%), Maruti Suzuki India Ltd. (5.18%), SBI Life Insurance Company Ltd. (5.12%)',
    total_holdings: '56',
    portfolio_summary: 'ELSS fund with 3-year lock-in for tax benefits, diversified across Financial, Auto, Healthcare, Technology',
    tax_ltcg: '12.5% on gains above ₹1.25 lakh/year for holdings > 12 months',
    tax_stcg: '20% on gains for holdings ≤ 12 months',
    elss_features: '3-year lock-in period, Tax saving under Section 80C, LTCG after lock-in period'
  }
};

console.log('Comprehensive data with', Object.keys(COMPREHENSIVE_DATA).length, 'schemes ready');
console.log('Schemes:', Object.values(COMPREHENSIVE_DATA).map(s => s.name).join(', '));

module.exports = { COMPREHENSIVE_DATA };
